### ISSUE TITLE
hey bruhhh whats happen???

### ISSUE THREAD

**Issue by NekoYasui** [AdlerVaz/AdlerVaz#1]
### join my server bruhh
https://discord.com/invite/yuXefsEBcJ

**Comment by AdlerVaz** [comment]
my account got hacked .... lol
i wont be using discord nomore .... i was happy to hv a frnd like u
9823965021 my number +91 is the indian code .... remember me lol
txt me on whatsapp if u get time

**Comment by NekoYasui** [comment]
i dont use whatsapp bruhh

**Comment by NekoYasui** [comment]
why you got hacked?

**Comment by AdlerVaz** [comment]
hmmmm
lol

**Comment by AdlerVaz** [comment]
okay so i quiet discord

**Comment by NekoYasui** [comment]
did you use the file???

**Comment by NekoYasui** [comment]
![image](https://user-images.githubusercontent.com/61488837/105385646-8ac06080-5c4e-11eb-8139-335804f662f0.png)

**Comment by AdlerVaz** [comment]
no

**Comment by AdlerVaz** [comment]
lol i didnt use it

**Comment by NekoYasui** [comment]
https://media.discordapp.net/attachments/797438840151212052/801860914491555871/n7kK05fjpz.gif?width=561&height=214

**Comment by AdlerVaz** [comment]
ohh i had dmed the guys
that they scam

**Comment by AdlerVaz** [comment]
maybe thats y

**Comment by NekoYasui** [comment]
lol..

**Comment by NekoYasui** [comment]
F

**Comment by NekoYasui** [comment]
you cant recover ur account?

**Comment by AdlerVaz** [comment]
i have my acc
but no use now

**Comment by AdlerVaz** [comment]
lol
i wont use discord again

**Comment by xkwm1** [comment]
bruh why

**Comment by NekoYasui** [comment]
looks like you click the file.. its a token stealer

**Comment by SC136** [comment]
😢

**Comment by NekoYasui** [comment]
1 click of it.. and it gonna run silent

**Comment by xkwm1** [comment]
is it a .exe or what?

**Comment by NekoYasui** [comment]
yea...

> is it a .exe or what?

**Comment by SC136** [comment]
then its a app

**Comment by xkwm1** [comment]
oh

**Comment by NekoYasui** [comment]
ialready warn adler that dont use the file.. :(

**Comment by SC136** [comment]
now what?

**Comment by xkwm1** [comment]
uh idk

**Comment by NekoYasui** [comment]
adler? you wont gonna use discord? how about ur ZeroTwo Bot?

**Comment by SC136** [comment]
oh yes what abt the bot?

**Comment by xkwm1** [comment]
You spent a lot of time coding that bot, I'd hate to see it go away.

**Comment by SC136** [comment]
yaa

**Comment by xkwm1** [comment]
@AdlerVaz

**Comment by SC136** [comment]
he is not reponding!

**Comment by xkwm1** [comment]
he's prob watching anime or something rn

**Comment by SC136** [comment]
oh

**Comment by NekoYasui** [comment]
I recommend to use OperaGX.. cuz token stealer cant get the password

**Comment by SC136** [comment]
hmm

**Comment by NekoYasui** [comment]
well, if you logged on discordapp they can get ur discord password

**Comment by SC136** [comment]
best option : enable 2fa

**Comment by xkwm1** [comment]
Well once you decided to check on here, just join the discord server (https://discord.gg/AkEEtHCqmN) and we can have a convo.

**Comment by SC136** [comment]
Yes
